<a href="https://colab.research.google.com/github/bimarshak7/learnTensorFlow/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Learn Tensorflow Fundamentals

In [ ]:
#import tensorflow 
import tensorflow as tf
tf.__version__

'2.8.2'

Tensoflow Constants

In [ ]:
  scaler = tf.constant(7)
  scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scaler.ndim

0

In [ ]:
  vector = tf.constant([1,2,3])
  vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
#matrix
matrix = tf.constant([[1,2,3],[4,5,7]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 7]], dtype=int32)>

In [ ]:
#matrix with dtype specified
matrix2 = tf.constant([[1,2,3],[4,5,7]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 7.]], dtype=float16)>

In [ ]:
print(matrix2)
print(matrix2.ndim)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 7.]], shape=(2, 3), dtype=float16)
2


In [ ]:
#create tensor constsnt
tensor = tf.constant( [
                       [[1,2,3],
                        [1,2,3]],
                       [[11,22,33],
                        [34,54,23]]
                       ])

In [ ]:
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 1  2  3]]

 [[11 22 33]
  [34 54 23]]], shape=(2, 2, 3), dtype=int32)
3


### Variables in tensorflow(tf.variable)

In [ ]:
scaler_var = tf.Variable(7)
vector_var = tf.Variable([1,2,3])
tensor_var = tf.Variable( [
                       [[1,2,3],
                        [1,2,3]],
                       [[11,22,33],
                        [34,54,23]]
                       ])
scaler_var,vector_var,tensor_var

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 1,  2,  3]],
 
        [[11, 22, 33],
         [34, 54, 23]]], dtype=int32)>)

In [ ]:
scaler_var.assign(10)
vector_var.assign([1,2,22])
print(scaler_var)
print(vector_var)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 1,  2, 22], dtype=int32)>


### Random Tensors

In [ ]:
test1 = tf.random.Generator.from_seed(123) #using seed for reproducibility
test1 = test1.normal(shape=(2, 3, 4))
test1
test2 = tf.random.Generator.from_seed(123) #using seed for reproducibility
test2 = test2.normal(shape=(2, 3, 4))

test1,test2,test1==test2

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[ 0.8673864 , -0.29899067, -0.93103355, -1.5828488 ],
         [ 1.2481192 , -0.67706424,  0.01912649, -0.29333332],
         [-0.35438988,  0.07048975, -0.4882456 , -0.56108433]],
 
        [[-0.9890895 , -0.47498497, -1.3177569 , -1.748288  ],
         [-1.6292503 ,  0.48826346, -1.8867823 ,  0.18151656],
         [ 0.24483992,  0.37554735,  1.6184237 ,  0.34223038]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[ 0.8673864 , -0.29899067, -0.93103355, -1.5828488 ],
         [ 1.2481192 , -0.67706424,  0.01912649, -0.29333332],
         [-0.35438988,  0.07048975, -0.4882456 , -0.56108433]],
 
        [[-0.9890895 , -0.47498497, -1.3177569 , -1.748288  ],
         [-1.6292503 ,  0.48826346, -1.8867823 ,  0.18151656],
         [ 0.24483992,  0.37554735,  1.6184237 ,  0.34223038]]],
       dtype=float32)>, <tf.Tensor: shape=(2, 3, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  Tru

In [ ]:
# Shuffle Tensor
original = tf.constant([
                               [1, 2],
                               [3, 4],
                               [5, 6],
                               [7, 8],
                               [9, 10]
])

tf.random.set_seed(21) # global level seed
shuffled = tf.random.shuffle(original)
print(original,shuffled)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]], shape=(5, 2), dtype=int32) tf.Tensor(
[[ 3  4]
 [ 1  2]
 [ 7  8]
 [ 9 10]
 [ 5  6]], shape=(5, 2), dtype=int32)


## Tensors from numpy array

In [ ]:
tf.ones((5,3)),tf.zeros((5,5))

(<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>)

In [ ]:
import numpy as np

num_A = np.arange(1,25,dtype=np.int32)
num_tensor = tf.constant(num_A,shape=(2,3,4))
num_A,num_tensor

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Get info from tensor

In [ ]:
rank_4 = tf.zeros(shape=[2,3,3,5,6])
rank_4

<tf.Tensor: shape=(2, 3, 3, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [ ]:
rank_4.shape,rank_4.ndim,tf.size(rank_4)

(TensorShape([2, 3, 3, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=540>)

In [ ]:
print("Data type: ",rank_4.dtype)
print("No. of dimensio (rank): ", rank_4.ndim)
print("Shape of tensor: ", rank_4.shape)
print("Elements along the 0 axis: ", rank_4.shape[0])
print("Elements along the last axis: ", rank_4.shape[-1])
print("Total no. of elements in the tensor: ",tf.size(rank_4).numpy())


Data type:  <dtype: 'float32'>
No. of dimensio (rank):  5
Shape of tensor:  (2, 3, 3, 5, 6)
Elements along the 0 axis:  2
Elements along the last axis:  6
Total no. of elements in the tensor:  540


### Tensors index
Same as python list indexing and slicing

In [ ]:
rank_4[:1,:2,::]

<tf.Tensor: shape=(1, 2, 3, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

## Basic operations

In [ ]:
tensor = tf.constant([[1,2],[3,4]])
tensor % 10 # +, -,* , /, %  
#original tensor remains unchanged, uses on;y CPU not GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10), tf.math.add(tensor,12) #uses GPU or TPU

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 14],
        [15, 16]], dtype=int32)>)

In [ ]:
### Matrix multiplication

In [ ]:
tf.matmul(tensor,tensor) #uses tf.linalg.matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor * tensor #elementwise multiplication, @ can be used for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
x = tf.constant([[1,2],[3,4],[5,6]])
y = tf.constant([[7,8,9],[10,11,12]])
z = tf.constant([[7,8],[10,12],[13,14],[15,16],[17,18],[19,20]])

In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
z

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 7,  8],
       [10, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]], dtype=int32)>

In [ ]:
tf.reshape(z,shape=(2,6)) , tf.transpose(z)

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 7,  8, 10, 12, 13, 14],
        [15, 16, 17, 18, 19, 20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 7, 10, 13, 15, 17, 19],
        [ 8, 12, 14, 16, 18, 20]], dtype=int32)>)

In [ ]:
x @ tf.reshape(z,shape=(2,6)) # @ does matrix multiplication in python}

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 37,  40,  44,  48,  51,  54],
       [ 81,  88,  98, 108, 115, 122],
       [125, 136, 152, 168, 179, 190]], dtype=int32)>

In [ ]:
tf.matmul(x, tf.transpose(z))

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 23,  34,  41,  47,  53,  59],
       [ 53,  78,  95, 109, 123, 137],
       [ 83, 122, 149, 171, 193, 215]], dtype=int32)>

**Dot Product**

In [ ]:
tf.tensordot(x,y,axes=1),tf.matmul(x,y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(x,y,axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  8,  9],
         [10, 11, 12]],

        [[14, 16, 18],
         [20, 22, 24]]],


       [[[21, 24, 27],
         [30, 33, 36]],

        [[28, 32, 36],
         [40, 44, 48]]],


       [[[35, 40, 45],
         [50, 55, 60]],

        [[42, 48, 54],
         [60, 66, 72]]]], dtype=int32)>

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [ ]:
np.inner(a,b)

array([[ 50,  68],
       [122, 167]])

In [ ]:
7+16+27,10+22+36

(50, 68)

In [ ]:
np.outer

<function numpy.outer>

In [ ]:
x.dtype

tf.int32

In [ ]:
tf.cast(x,dtype=tf.float32) #change data type

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

## Aggregating tensors
 - Abs
 - Mean
 - Max
 - Min and so on

In [ ]:
tens = tf.constant([-1,-2,-3])
tf.abs(tens)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
A = tf.constant(np.random.randint(0,100,size=50),dtype=tf.float32)
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([49., 96., 29.,  9., 47., 91., 46., 51., 59., 19., 89., 69., 76.,
        5., 99., 15., 91., 38., 38.,  1., 43., 37.,  0.,  1., 59., 30.,
       34.,  7., 33., 25., 76., 55., 31., 49., 49.,  3.,  8., 77., 66.,
       36., 80., 53., 60., 48., 71., 75., 74., 81., 16., 59.],
      dtype=float32)>

In [ ]:
tf.size(A),A.ndim, A.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [ ]:
print("Mean: ",tf.reduce_mean(A).numpy())
print("SD: ",tf.math.reduce_std(A).numpy()) 
print("Variance: ",tf.math.reduce_variance(A).numpy()) #mean

Mean:  47.06
SD:  27.865685
Variance:  776.4964


In [ ]:
tf.reduce_max(A),tf.reduce_min(A)

(<tf.Tensor: shape=(), dtype=float32, numpy=99.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>)

## Positional max,min

In [ ]:
tf.random.set_seed(12)
A = tf.random.uniform(shape=[50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.47720265, 0.33357763, 0.4960823 , 0.48351312, 0.2963959 ,
       0.69444907, 0.68488   , 0.6662284 , 0.07551682, 0.06608915,
       0.91428673, 0.21982336, 0.066468  , 0.37987065, 0.88209164,
       0.73124087, 0.59181285, 0.9785874 , 0.0937705 , 0.37701082,
       0.2055552 , 0.2800591 , 0.44172525, 0.9199766 , 0.49873018,
       0.10266078, 0.12177575, 0.10520744, 0.22547913, 0.39156199,
       0.5587522 , 0.7095549 , 0.04214132, 0.03028095, 0.14591146,
       0.7897457 , 0.52633774, 0.8487345 , 0.08758485, 0.5727763 ,
       0.74252594, 0.63061965, 0.03749514, 0.0432719 , 0.13088238,
       0.6540686 , 0.9438777 , 0.65461504, 0.10520577, 0.8353534 ],
      dtype=float32)>

In [ ]:
tf.argmax(A,axis=0),A[tf.argmax(A,axis=0)],tf.reduce_max(A)

(<tf.Tensor: shape=(), dtype=int64, numpy=17>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9785874>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9785874>)

In [ ]:
tf.argmin(A,axis=0),A[tf.argmin(A,axis=0)],tf.reduce_min(A)

(<tf.Tensor: shape=(), dtype=int64, numpy=33>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.030280948>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.030280948>)

In [ ]:
B = tf.constant(tf.random.uniform(shape=[100]),shape=(1,2,1,1,50))
B

<tf.Tensor: shape=(1, 2, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.32095957, 0.7189348 , 0.87707686, 0.47581577, 0.7003732 ,
           0.7321279 , 0.25916302, 0.6902908 , 0.9872663 , 0.8601574 ,
           0.22054565, 0.84840035, 0.29193854, 0.26677644, 0.75828254,
           0.12371647, 0.00212812, 0.68888617, 0.38517427, 0.12188411,
           0.56316876, 0.05912185, 0.3157003 , 0.8786137 , 0.8753121 ,
           0.7160096 , 0.9419296 , 0.44044304, 0.7505392 , 0.01177239,
           0.6105257 , 0.6891991 , 0.91607106, 0.55492866, 0.55074644,
           0.07777715, 0.76308095, 0.00216663, 0.5055393 , 0.8803278 ,
           0.04833901, 0.04366612, 0.9809506 , 0.27405775, 0.5914726 ,
           0.4927982 , 0.86158025, 0.23493552, 0.27736568, 0.38115633]]],


        [[[0.60218453, 0.53051066, 0.48460412, 0.40210152, 0.35604906,
           0.91844916, 0.74156547, 0.1841731 , 0.98216033, 0.32677376,
           0.59047174, 0.2459085 , 0.24897099, 0.04138458, 0.2010895 ,
           0.5

In [ ]:
B_squeezed = tf.squeeze(B)
B_squeezed.shape

TensorShape([2, 50])

## One hot encoding

In [ ]:
some_list = [1,2,3,1,4,2,3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=4, on_value="yo", off_value="oh no")

<tf.Tensor: shape=(7, 4), dtype=string, numpy=
array([[b'oh no', b'yo', b'oh no', b'oh no'],
       [b'oh no', b'oh no', b'yo', b'oh no'],
       [b'oh no', b'oh no', b'oh no', b'yo'],
       [b'oh no', b'yo', b'oh no', b'oh no'],
       [b'oh no', b'oh no', b'oh no', b'oh no'],
       [b'oh no', b'oh no', b'yo', b'oh no'],
       [b'oh no', b'oh no', b'oh no', b'yo']], dtype=object)>

## Misc
log,exp, pow

In [ ]:
C = tf.range(1,10)
C = tf.cast(C, dtype=tf.float32)

In [ ]:
tf.math.sqrt(C),tf.math.log(C),tf.math.exp(C)

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([2.7182817e+00, 7.3890562e+00, 2.0085537e+01, 5.4598148e+01,
        1.4841316e+02, 4.0342880e+02, 1.0966332e+03, 2.9809580e+03,
        8.1030840e+03], dtype=float32)>)

## Tensors and numpy

In [ ]:
D = tf.constant(np.array([1,2,3,4,565,7,7,5]))
D

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([  1,   2,   3,   4, 565,   7,   7,   5])>

In [ ]:
np.array(D)

array([  1,   2,   3,   4, 565,   7,   7,   5])

In [ ]:
E = tf.constant(np.array([1,2,3,4,5]))
F = tf.constant([1,2,3,4,5])
E.dtype, F.dtype
#tensor from numpy array-> (int/float)64,
#tensor from list -> (int/float)32 

(tf.int64, tf.int32)

## Using GPU

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Jul 14 16:33:37 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------